// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShopQuanAo.Data;

#nullable disable

namespace ShopQuanAo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251021020819_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ShopQuanAo.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOnSale")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("OldPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "men",
                            CreatedDate = new DateTime(2025, 10, 21, 9, 8, 18, 546, DateTimeKind.Local).AddTicks(9414),
                            Description = "Áo thun nam chất liệu cotton cao cấp, thoáng mát",
                            ImageUrl = "~/images/product_1.png",
                            IsAvailable = true,
                            IsFeatured = true,
                            IsOnSale = true,
                            Name = "Áo Thun Nam Basic",
                            OldPrice = 250000m,
                            Price = 199000m,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 2,
                            Category = "women",
                            CreatedDate = new DateTime(2025, 10, 21, 9, 8, 18, 546, DateTimeKind.Local).AddTicks(9419),
                            Description = "Áo sơ mi nữ công sở sang trọng",
                            ImageUrl = "~/images/product_2.png",
                            IsAvailable = true,
                            IsFeatured = true,
                            IsOnSale = false,
                            Name = "Áo Sơ Mi Nữ",
                            Price = 350000m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 3,
                            Category = "men",
                            CreatedDate = new DateTime(2025, 10, 21, 9, 8, 18, 546, DateTimeKind.Local).AddTicks(9423),
                            Description = "Quần jeans nam form slim fit",
                            ImageUrl = "~/images/product_3.png",
                            IsAvailable = true,
                            IsFeatured = false,
                            IsOnSale = false,
                            Name = "Quần Jeans Nam",
                            Price = 450000m,
                            StockQuantity = 75
                        },
                        new
                        {
                            Id = 4,
                            Category = "women",
                            CreatedDate = new DateTime(2025, 10, 21, 9, 8, 18, 546, DateTimeKind.Local).AddTicks(9427),
                            Description = "Váy đầm nữ thời trang cao cấp",
                            ImageUrl = "~/images/product_4.png",
                            IsAvailable = true,
                            IsFeatured = true,
                            IsOnSale = true,
                            Name = "Váy Đầm Nữ",
                            OldPrice = 650000m,
                            Price = 550000m,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 5,
                            Category = "men",
                            CreatedDate = new DateTime(2025, 10, 21, 9, 8, 18, 546, DateTimeKind.Local).AddTicks(9430),
                            Description = "Áo khoác nam phong cách Hàn Quốc",
                            ImageUrl = "~/images/product_5.png",
                            IsAvailable = true,
                            IsFeatured = false,
                            IsOnSale = false,
                            Name = "Áo Khoác Nam",
                            Price = 650000m,
                            StockQuantity = 45
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
