// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShopQuanAo.Data;

#nullable disable

namespace ShopQuanAo.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251110182505_SeedShippingFees")]
    partial class SeedShippingFees
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "2",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "admin-001",
                            RoleId = "1"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ShopQuanAo.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("AvatarFileName")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "admin-001",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3891cd90-0945-4d08-a014-3248994dd981",
                            CreatedDate = new DateTime(2025, 11, 11, 1, 25, 4, 352, DateTimeKind.Local).AddTicks(1169),
                            Email = "admin@shopquanao.com",
                            EmailConfirmed = true,
                            FullName = "Administrator",
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@SHOPQUANAO.COM",
                            NormalizedUserName = "ADMIN@SHOPQUANAO.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEBM+cV005lbJT+f9AFRwDDSsEnEJ5w+gtIrIgFtt3Ylj+UaElZEGvJtwqPSdzD35Zw==",
                            PhoneNumber = "0123456789",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f69a47c6-dc84-4046-89ae-8036cce849cf",
                            TwoFactorEnabled = false,
                            UserName = "admin@shopquanao.com"
                        });
                });

            modelBuilder.Entity("ShopQuanAo.Models.ContactMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsRead")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReplied")
                        .HasColumnType("bit");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<DateTime?>("ReadAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RepliedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RepliedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ReplyBody")
                        .HasMaxLength(8000)
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReplySubject")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Website")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.ToTable("ContactMessages");
                });

            modelBuilder.Entity("ShopQuanAo.Models.Coupon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AllowedCategoriesCsv")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("DiscountType")
                        .HasColumnType("int");

                    b.Property<decimal>("DiscountValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<decimal?>("MinOrderAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Scope")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Coupons");
                });

            modelBuilder.Entity("ShopQuanAo.Models.FlashSaleItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("FlashPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("FlashSaleItems");
                });

            modelBuilder.Entity("ShopQuanAo.Models.MomoTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Deeplink")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("OrderInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PayUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QrCodeUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ResultCode")
                        .HasColumnType("int");

                    b.Property<string>("Signature")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.Property<string>("TransactionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("MomoTransactions");
                });

            modelBuilder.Entity("ShopQuanAo.Models.Order", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CouponCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("ShippingFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VnPayOrderId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("VnPayPaidAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VnPayResponseCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("VnPayTransactionId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("OrderCode")
                        .IsUnique();

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("ShopQuanAo.Models.OrderItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("OrderId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("ProductImage")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("ShopQuanAo.Models.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Slug")
                        .HasMaxLength(220)
                        .HasColumnType("nvarchar(220)");

                    b.Property<string>("Thumbnail")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Slug");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("ShopQuanAo.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("bit");

                    b.Property<bool>("IsOnSale")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal?>("OldPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "men",
                            CreatedDate = new DateTime(2025, 11, 11, 1, 25, 4, 433, DateTimeKind.Local).AddTicks(4526),
                            Description = "Áo thun nam chất liệu cotton cao cấp, thoáng mát",
                            ImageUrl = "~/images/product_1.png",
                            IsAvailable = true,
                            IsFeatured = true,
                            IsOnSale = true,
                            Name = "Áo Thun Nam Basic",
                            OldPrice = 250000m,
                            Price = 199000m,
                            StockQuantity = 100
                        },
                        new
                        {
                            Id = 2,
                            Category = "women",
                            CreatedDate = new DateTime(2025, 11, 11, 1, 25, 4, 433, DateTimeKind.Local).AddTicks(4531),
                            Description = "Áo sơ mi nữ công sở sang trọng",
                            ImageUrl = "~/images/product_2.png",
                            IsAvailable = true,
                            IsFeatured = true,
                            IsOnSale = false,
                            Name = "Áo Sơ Mi Nữ",
                            Price = 350000m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Id = 3,
                            Category = "men",
                            CreatedDate = new DateTime(2025, 11, 11, 1, 25, 4, 433, DateTimeKind.Local).AddTicks(4537),
                            Description = "Quần jeans nam form slim fit",
                            ImageUrl = "~/images/product_3.png",
                            IsAvailable = true,
                            IsFeatured = false,
                            IsOnSale = false,
                            Name = "Quần Jeans Nam",
                            Price = 450000m,
                            StockQuantity = 75
                        },
                        new
                        {
                            Id = 4,
                            Category = "women",
                            CreatedDate = new DateTime(2025, 11, 11, 1, 25, 4, 433, DateTimeKind.Local).AddTicks(4544),
                            Description = "Váy đầm nữ thời trang cao cấp",
                            ImageUrl = "~/images/product_4.png",
                            IsAvailable = true,
                            IsFeatured = true,
                            IsOnSale = true,
                            Name = "Váy Đầm Nữ",
                            OldPrice = 650000m,
                            Price = 550000m,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 5,
                            Category = "men",
                            CreatedDate = new DateTime(2025, 11, 11, 1, 25, 4, 433, DateTimeKind.Local).AddTicks(4548),
                            Description = "Áo khoác nam phong cách Hàn Quốc",
                            ImageUrl = "~/images/product_5.png",
                            IsAvailable = true,
                            IsFeatured = false,
                            IsOnSale = false,
                            Name = "Áo Khoác Nam",
                            Price = 650000m,
                            StockQuantity = 45
                        });
                });

            modelBuilder.Entity("ShopQuanAo.Models.ShippingFee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Fee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ProvinceName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ProvinceName");

                    b.ToTable("ShippingFees");

                    b.HasData(
                        new
                        {
                            Id = 101,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Nội thành & lân cận",
                            Fee = 35000m,
                            IsActive = true,
                            ProvinceName = "Thành phố Hà Nội"
                        },
                        new
                        {
                            Id = 102,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Nội thành & lân cận",
                            Fee = 35000m,
                            IsActive = true,
                            ProvinceName = "Thành phố Hồ Chí Minh"
                        },
                        new
                        {
                            Id = 103,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Nội thành & lân cận",
                            Fee = 35000m,
                            IsActive = true,
                            ProvinceName = "Thành phố Đà Nẵng"
                        },
                        new
                        {
                            Id = 104,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Nội thành & lân cận",
                            Fee = 35000m,
                            IsActive = true,
                            ProvinceName = "Thành phố Hải Phòng"
                        },
                        new
                        {
                            Id = 105,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Nội thành & lân cận",
                            Fee = 35000m,
                            IsActive = true,
                            ProvinceName = "Thành phố Cần Thơ"
                        },
                        new
                        {
                            Id = 106,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tỉnh miền núi",
                            Fee = 55000m,
                            IsActive = true,
                            ProvinceName = "Tỉnh Hà Giang"
                        },
                        new
                        {
                            Id = 107,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tỉnh miền núi",
                            Fee = 55000m,
                            IsActive = true,
                            ProvinceName = "Tỉnh Cao Bằng"
                        },
                        new
                        {
                            Id = 108,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tỉnh miền núi",
                            Fee = 55000m,
                            IsActive = true,
                            ProvinceName = "Tỉnh Bắc Kạn"
                        },
                        new
                        {
                            Id = 109,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tỉnh miền núi",
                            Fee = 55000m,
                            IsActive = true,
                            ProvinceName = "Tỉnh Tuyên Quang"
                        },
                        new
                        {
                            Id = 110,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tỉnh miền núi",
                            Fee = 55000m,
                            IsActive = true,
                            ProvinceName = "Tỉnh Lào Cai"
                        },
                        new
                        {
                            Id = 111,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tỉnh miền núi",
                            Fee = 55000m,
                            IsActive = true,
                            ProvinceName = "Tỉnh Điện Biên"
                        },
                        new
                        {
                            Id = 112,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tỉnh miền núi",
                            Fee = 55000m,
                            IsActive = true,
                            ProvinceName = "Tỉnh Lai Châu"
                        },
                        new
                        {
                            Id = 113,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tỉnh miền núi",
                            Fee = 55000m,
                            IsActive = true,
                            ProvinceName = "Tỉnh Sơn La"
                        },
                        new
                        {
                            Id = 114,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tỉnh miền núi",
                            Fee = 55000m,
                            IsActive = true,
                            ProvinceName = "Tỉnh Yên Bái"
                        },
                        new
                        {
                            Id = 115,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tỉnh miền núi",
                            Fee = 55000m,
                            IsActive = true,
                            ProvinceName = "Tỉnh Hòa Bình"
                        },
                        new
                        {
                            Id = 116,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Vùng núi phía Bắc",
                            Fee = 55000m,
                            IsActive = true,
                            ProvinceName = "Tỉnh Lạng Sơn"
                        },
                        new
                        {
                            Id = 117,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tây Nguyên",
                            Fee = 55000m,
                            IsActive = true,
                            ProvinceName = "Tỉnh Kon Tum"
                        },
                        new
                        {
                            Id = 118,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tây Nguyên",
                            Fee = 55000m,
                            IsActive = true,
                            ProvinceName = "Tỉnh Gia Lai"
                        },
                        new
                        {
                            Id = 119,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tây Nguyên",
                            Fee = 55000m,
                            IsActive = true,
                            ProvinceName = "Tỉnh Đắk Lắk"
                        },
                        new
                        {
                            Id = 120,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tây Nguyên",
                            Fee = 55000m,
                            IsActive = true,
                            ProvinceName = "Tỉnh Đắk Nông"
                        },
                        new
                        {
                            Id = 121,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Tây Nguyên",
                            Fee = 55000m,
                            IsActive = true,
                            ProvinceName = "Tỉnh Lâm Đồng"
                        },
                        new
                        {
                            Id = 122,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ven biển",
                            Fee = 45000m,
                            IsActive = true,
                            ProvinceName = "Tỉnh Quảng Ninh"
                        },
                        new
                        {
                            Id = 123,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Fee = 45000m,
                            IsActive = true,
                            ProvinceName = "Tỉnh Bắc Giang"
                        },
                        new
                        {
                            Id = 124,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Fee = 45000m,
                            IsActive = true,
                            ProvinceName = "Tỉnh Phú Thọ"
                        },
                        new
                        {
                            Id = 125,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Fee = 45000m,
                            IsActive = true,
                            ProvinceName = "Tỉnh Vĩnh Phúc"
                        },
                        new
                        {
                            Id = 126,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Fee = 45000m,
                            IsActive = true,
                            ProvinceName = "Tỉnh Thái Nguyên"
                        },
                        new
                        {
                            Id = 127,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Fee = 45000m,
                            IsActive = true,
                            ProvinceName = "Tỉnh Bắc Ninh"
                        },
                        new
                        {
                            Id = 128,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Fee = 45000m,
                            IsActive = true,
                            ProvinceName = "Tỉnh Hải Dương"
                        },
                        new
                        {
                            Id = 129,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Fee = 45000m,
                            IsActive = true,
                            ProvinceName = "Tỉnh Hưng Yên"
                        },
                        new
                        {
                            Id = 130,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Fee = 45000m,
                            IsActive = true,
                            ProvinceName = "Tỉnh Thái Bình"
                        },
                        new
                        {
                            Id = 131,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Fee = 45000m,
                            IsActive = true,
                            ProvinceName = "Tỉnh Hà Nam"
                        },
                        new
                        {
                            Id = 132,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Fee = 45000m,
                            IsActive = true,
                            ProvinceName = "Tỉnh Nam Định"
                        },
                        new
                        {
                            Id = 133,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Fee = 45000m,
                            IsActive = true,
                            ProvinceName = "Tỉnh Ninh Bình"
                        },
                        new
                        {
                            Id = 134,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Fee = 45000m,
                            IsActive = true,
                            ProvinceName = "Tỉnh Thanh Hóa"
                        },
                        new
                        {
                            Id = 135,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Fee = 45000m,
                            IsActive = true,
                            ProvinceName = "Tỉnh Nghệ An"
                        },
                        new
                        {
                            Id = 136,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Fee = 45000m,
                            IsActive = true,
                            ProvinceName = "Tỉnh Hà Tĩnh"
                        },
                        new
                        {
                            Id = 137,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Fee = 45000m,
                            IsActive = true,
                            ProvinceName = "Tỉnh Quảng Bình"
                        },
                        new
                        {
                            Id = 138,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Fee = 45000m,
                            IsActive = true,
                            ProvinceName = "Tỉnh Quảng Trị"
                        },
                        new
                        {
                            Id = 139,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Fee = 45000m,
                            IsActive = true,
                            ProvinceName = "Tỉnh Thừa Thiên Huế"
                        },
                        new
                        {
                            Id = 140,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Fee = 45000m,
                            IsActive = true,
                            ProvinceName = "Tỉnh Quảng Nam"
                        },
                        new
                        {
                            Id = 141,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Fee = 45000m,
                            IsActive = true,
                            ProvinceName = "Tỉnh Quảng Ngãi"
                        },
                        new
                        {
                            Id = 142,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Fee = 45000m,
                            IsActive = true,
                            ProvinceName = "Tỉnh Bình Định"
                        },
                        new
                        {
                            Id = 143,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Fee = 45000m,
                            IsActive = true,
                            ProvinceName = "Tỉnh Phú Yên"
                        },
                        new
                        {
                            Id = 144,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ven biển",
                            Fee = 45000m,
                            IsActive = true,
                            ProvinceName = "Tỉnh Khánh Hòa"
                        },
                        new
                        {
                            Id = 145,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ven biển",
                            Fee = 45000m,
                            IsActive = true,
                            ProvinceName = "Tỉnh Ninh Thuận"
                        },
                        new
                        {
                            Id = 146,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ven biển",
                            Fee = 45000m,
                            IsActive = true,
                            ProvinceName = "Tỉnh Bình Thuận"
                        },
                        new
                        {
                            Id = 147,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Fee = 45000m,
                            IsActive = true,
                            ProvinceName = "Tỉnh Bình Phước"
                        },
                        new
                        {
                            Id = 148,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Fee = 45000m,
                            IsActive = true,
                            ProvinceName = "Tỉnh Tây Ninh"
                        },
                        new
                        {
                            Id = 149,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Fee = 45000m,
                            IsActive = true,
                            ProvinceName = "Tỉnh Bình Dương"
                        },
                        new
                        {
                            Id = 150,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Fee = 45000m,
                            IsActive = true,
                            ProvinceName = "Tỉnh Đồng Nai"
                        },
                        new
                        {
                            Id = 151,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ven biển",
                            Fee = 45000m,
                            IsActive = true,
                            ProvinceName = "Tỉnh Bà Rịa - Vũng Tàu"
                        },
                        new
                        {
                            Id = 152,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Fee = 45000m,
                            IsActive = true,
                            ProvinceName = "Tỉnh Long An"
                        },
                        new
                        {
                            Id = 153,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Fee = 45000m,
                            IsActive = true,
                            ProvinceName = "Tỉnh Tiền Giang"
                        },
                        new
                        {
                            Id = 154,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Fee = 45000m,
                            IsActive = true,
                            ProvinceName = "Tỉnh Bến Tre"
                        },
                        new
                        {
                            Id = 155,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Fee = 45000m,
                            IsActive = true,
                            ProvinceName = "Tỉnh Trà Vinh"
                        },
                        new
                        {
                            Id = 156,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Fee = 45000m,
                            IsActive = true,
                            ProvinceName = "Tỉnh Vĩnh Long"
                        },
                        new
                        {
                            Id = 157,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Fee = 45000m,
                            IsActive = true,
                            ProvinceName = "Tỉnh Đồng Tháp"
                        },
                        new
                        {
                            Id = 158,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Fee = 45000m,
                            IsActive = true,
                            ProvinceName = "Tỉnh An Giang"
                        },
                        new
                        {
                            Id = 159,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ven biển",
                            Fee = 45000m,
                            IsActive = true,
                            ProvinceName = "Tỉnh Kiên Giang"
                        },
                        new
                        {
                            Id = 160,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "",
                            Fee = 45000m,
                            IsActive = true,
                            ProvinceName = "Tỉnh Hậu Giang"
                        },
                        new
                        {
                            Id = 161,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ven biển",
                            Fee = 45000m,
                            IsActive = true,
                            ProvinceName = "Tỉnh Sóc Trăng"
                        },
                        new
                        {
                            Id = 162,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ven biển",
                            Fee = 45000m,
                            IsActive = true,
                            ProvinceName = "Tỉnh Bạc Liêu"
                        },
                        new
                        {
                            Id = 163,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Ven biển",
                            Fee = 45000m,
                            IsActive = true,
                            ProvinceName = "Tỉnh Cà Mau"
                        });
                });

            modelBuilder.Entity("ShopQuanAo.Models.Slide", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Slides");
                });

            modelBuilder.Entity("ShopQuanAo.Models.WishlistItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ApplicationUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("ApplicationUserId", "ProductId")
                        .IsUnique();

                    b.ToTable("WishlistItems");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ShopQuanAo.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ShopQuanAo.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShopQuanAo.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ShopQuanAo.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShopQuanAo.Models.FlashSaleItem", b =>
                {
                    b.HasOne("ShopQuanAo.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ShopQuanAo.Models.OrderItem", b =>
                {
                    b.HasOne("ShopQuanAo.Models.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("ShopQuanAo.Models.WishlistItem", b =>
                {
                    b.HasOne("ShopQuanAo.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ShopQuanAo.Models.Order", b =>
                {
                    b.Navigation("OrderItems");
                });
#pragma warning restore 612, 618
        }
    }
}
